---
abstract: 'Inject modules into a CPAN::Mini mirror.'
author:
  - 'Shawn Sorichetti <ssoriche@coloredblocks.net>'
  - 'Andy Armstrong <andy@hexten.net>'
  - 'Christian Walde <walde.christian@googlemail.com'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Mini-Inject
provides:
  CPAN::Mini::Inject:
    file: lib/CPAN/Mini/Inject.pm
    version: 0.28_02
  CPAN::Mini::Inject::Config:
    file: lib/CPAN/Mini/Inject/Config.pm
    version: 0.28_02
requires:
  Archive::Tar: 0
  CPAN::Checksums: 0
  CPAN::Mini: 0.32
  Carp: 0
  Compress::Zlib: 0
  Env: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 2.07
  File::Slurp: 0
  File::Spec: 2.07
  File::Spec::Functions: 0
  File::Temp: 0
  Getopt::Long: 0
  HTTP::Server::Simple: 0.07
  IO::Zlib: 0
  LWP::Simple: 0
  Module::Build::ModuleInfo: 0
  Pod::Usage: 0
  Test::More: 0
  YAML: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CPAN-Mini-Inject
  license: http://dev.perl.org/licenses/
  repository: 'git://github.com/wchristian/CPAN--Mini--Inject.git (fetch)'
version: 0.28_02
