#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-Mini-Inject
version:      0.16
version_from: lib/CPAN/Mini/Inject.pm
installdirs:  site
requires:
    CPAN::Checksums:               0
    Test::More:                    0
    CPAN::Mini:                    0.32
    LWP::Simple:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
