--- #YAML:1.0
name:               CPAN-Mini-Inject
version:            0.23
abstract:           Inject modules into a CPAN::Mini mirror.
author:
    - Shawn Sorichetti <ssoriche@coloredblocks.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Tar:         0
    Compress::Zlib:       0
    CPAN::Checksums:      0
    CPAN::Mini:           0.32
    HTTP::Server::Simple:  0.07
    IO::Zlib:             0
    LWP::Simple:          0
    Test::More:           0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
