# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-Mini-Inject
version:      0.18
version_from: lib/CPAN/Mini/Inject.pm
installdirs:  site
requires:
    Compress::Zlib:                0
    CPAN::Checksums:               0
    CPAN::Mini:                    0.32
    HTTP::Server::Simple:          0.07
    LWP::Simple:                   0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
