---
name: CPAN-Mini-Inject
version: 0.26
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: Inject modules into a CPAN::Mini mirror.
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CPAN-Mini-Inject
  license: http://dev.perl.org/licenses/
  repository: git://github.com/AndyA/CPAN--Mini--Inject.git
requires:
  Archive::Tar: 0
  CPAN::Checksums: 0
  CPAN::Mini: 0.32
  Carp: 0
  Compress::Zlib: 0
  Env: 0
  File::Basename: 0
  File::Copy: 0
  File::Path: 2.07
  File::Spec: 2.07
  File::Spec::Functions: 0
  Getopt::Long: 0
  HTTP::Server::Simple: 0.07
  IO::Zlib: 0
  LWP::Simple: 0
  Pod::Usage: 0
  Test::More: 0
  YAML: 0
provides:
  CPAN::Mini::Inject:
    file: lib/CPAN/Mini/Inject.pm
    version: 0.26
  CPAN::Mini::Inject::Config:
    file: lib/CPAN/Mini/Inject/Config.pm
    version: 0.26
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
